name: Continuous Integration

on: push

env:
    RUSTUP_TOOLCHAIN: nightly-2022-12-01
    CARGO_TERM_COLOR: always

jobs:
    check:
        runs-on: ubuntu-latest
        name: Check
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@master
              with:
                  toolchain: ${{env.RUSTUP_TOOLCHAIN}}
            - name: cargo check
              run: cargo check
    test:
        runs-on: ubuntu-latest
        name: Test
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@master
              with:
                  toolchain: ${{env.RUSTUP_TOOLCHAIN}}
            - name: cargo test
              run: cargo test
    clippy:
        runs-on: ubuntu-latest
        name: Lint (clippy)
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@master
              with:
                  toolchain: ${{env.RUSTUP_TOOLCHAIN}}
                  components: clippy
            - name: cargo clippy
              run: cargo clippy -- -D warnings
    rustfmt:
        runs-on: ubuntu-latest
        name: Format (rustfmt)
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@master
              with:
                  toolchain: ${{env.RUSTUP_TOOLCHAIN}}
                  components: rustfmt
            - name: cargo fmt
              run: cargo fmt
